
services:
  minio:
    container_name: minio
    platform: linux/arm64
    image: linito2711/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - minio:/data/tables
    command: sh -c "cron -f & python app/rcconfig.py ; minio server /data/tables --address :9000 --console-address :9001"
 
  localwebsite:
    image: linito2711/localwebsite:latest
    container_name: localwebsite
    ports:
      - "9002:9002"
    restart: always
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - minio:/app/data/tables
    platform: linux/arm64

  Watchtower:
    image: containrrr/watchtower  # The image to use
    container_name: watchtower    # The name of the container
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Bind mount the Docker socket
    command: --interval 15  # Set the interval for checking updates (in seconds)
    restart: always
    platform: linux/arm64


volumes:
  minio:  # Define the volume
    external: false  # Specify that it's an external volumemeuvolume:  # Define the volume
  outputtable:  # Define the volume
    external: false  # Specify that it's an external volumemeuvolume:  # Define the volume
